site_name: EyesDrive Developers Documentation
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: black
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
plugin:
  - tags

copyright: Copyright &copy; 2019 - 2022 EyesDrive Technologies

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


nav:
    - Home: 'index.md'
    - 'Understanding the eyes': 
      - 'understanding/index.md'
      - 'understanding/biosignals.md'
      - 'understanding/eog.md'
      - 'understanding/electrodes.md'
    - 'Getting Started':
        - 'getting-started/dependencies.md'
        - 'getting-started/simulator.md'
        - 'getting-started/testing.md'
    - 'Integrate':
      - 'Integrate via EDK': 'integrate/via-edk.md'
      - 'Integrate via SIP': 'integrate/via-sip.md'
      - 'Standalone integration': 'integrate/standalone.md'
